id: P009248
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16565
  title: མི་ཉག་སྨྱུག་རྫོང་།
  author: ''
  volumes:
    0434c4ce097349b781d5471003355bd1:
      image_group_id: I2PD18710
      title: ''
      volume_number: 1
      total_pages: 228
