id: P009248
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-19 19:29:54.032540
source_metadata:
  id: bdr:W1KG16565
  title: མི་ཉག་སྨྱུག་རྫོང་།
  author: ''
  volumes:
    0434c4ce097349b781d5471003355bd1:
      image_group_id: I2PD18710
      title: ''
      volume_number: 1
      total_pages: 228
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
